// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx5v3WfmZ5WMb-jtiRiZ0Q6vlsqttpj9A',
    appId: '1:161759847751:web:e79c7802f11a94dbf45862',
    messagingSenderId: '161759847751',
    projectId: 'copify01',
    authDomain: 'copify01.firebaseapp.com',
    storageBucket: 'copify01.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFXVlafd-MReEuL9e_SsXCpyHw8GnL2-4',
    appId: '1:161759847751:android:84786ded02b4fa19f45862',
    messagingSenderId: '161759847751',
    projectId: 'copify01',
    storageBucket: 'copify01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgK_ZvIsELMYiBQ4zZzZHL9Damkyon1cY',
    appId: '1:161759847751:ios:0634e73a22cb8d37f45862',
    messagingSenderId: '161759847751',
    projectId: 'copify01',
    storageBucket: 'copify01.firebasestorage.app',
    iosBundleId: 'com.example.copyify',
  );
}
